apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
        - name: celery
          image: marianadeem03/django-image:v1.0.1
          imagePullPolicy: Always
          workingDir: /code
          command: ["celery", "-A", "config.celery", "worker", "--loglevel=info"]
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "config.settings"
            - name: CELERY_BROKER_URL
              value: "redis://redis:6379/0"
            - name: CELERY_RESULT_BACKEND
              value: "redis://redis:6379/0"
---
apiVersion: v1
kind: Service
metadata:
  name: celery-worker
spec:
  selector:
    app: celery
  ports:
    - protocol: TCP
      port: 5555
