apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: marianadeem03/django-image:v1.0
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "config.settings"
            - name: CELERY_BROKER_URL
              value: "redis://redis:6379/0"
            - name: CELERY_RESULT_BACKEND
              value: "redis://redis:6379/0"
---
apiVersion: v1
kind: Service
metadata:
  name: django
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
